### ISSUE TITLE
azure_stateful_node: Import of existing VMs?

### ISSUE THREAD

**Issue by jfunke4** [spotinst/spot-ansible-cloud-modules#12]
Is it possible to import a existing VM as a stateful node into spot.io via the Ansible module azure_stateful_node?
Or can you use this module just to create a new stateful node?

**Comment by anuragsharma-123** [comment]
@jfunke4 - Currently only new stateful node creation is supported. Sharing your request with PMs for their evaluation.

**Comment by jfunke4** [comment]
@anuragsharma-123 - Thank you for the clarification.

**Comment by anuragsharma-123** [comment]
@jfunke4 - We are adding support for VM Import. Will post here when it is available.
