### ISSUE TITLE
Feature Request: Collection-level Metadata for better execution-environment handling

### ISSUE THREAD

**Issue by nwerker** [spotinst/spot-ansible-cloud-modules#13]
Dear maintainers,

Please add and maintain the python requirements (modules: spotinst-sdk2) of the collection in its "Collection-level Metadata" so that people can more easily use the collection in execution-environments when using it with awx or ansible automation controller.

The Collection-level Metadata makes it more easy to include the collection in execution-environments, since the python dependencies will be automatically installed, when building the execution-environment with ansible-builder.

As you are already maintaining the requirements.txt file, this would simply require a few more lines of yaml in form of an execution-environment.yml file. I would be glad to contribute a pull request with the necessary lines of code later today. I'm also willing to contribute to testing and building example execution environments in the future, even if it involves an increase in dependencies.

If you need further information about the Collection-level Metadata here is some documentation from the ansible-builder project [Documentation](https://ansible-builder.readthedocs.io/en/stable/collection_metadata.html).

Thanks in advance

**Comment by anuragsharma-123** [comment]
@nwerker - Thanks for posting this. It is a good idea. I will incorporate your PR.

**Comment by anuragsharma-123** [comment]
Hi @nwerker - I have released this PR as part of one of my other PRs. Please check. Shall I close the PR created by you.

**Comment by nwerker** [comment]
@anuragsharma-123 looks great! Thank you for incorporating it! Feel free to close the PR :)

**Comment by nwerker** [comment]
closed with #15
